name: video-editor-api
services:
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: ${DATABASE_PASS}
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - 6000:5432
  app:
    image: video-editor-api:latest
    ports:
      - 10000:${APP_PORT}
    environment:
      - APP_ENV=${APP_ENV}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_COMPONENT=${APP_COMPONENT}
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - SERVICE_READINESS_TIMEOUT=${SERVICE_READINESS_TIMEOUT}
    volumes:
      - ./scripts:/scripts
    depends_on:
      - postgres
